Near-One/omni-bridge

near/nep141-locker/src/lib.rs

log_metadata calls MPC signing service which requires 250 tgas

Fix gas requirements for log_metadata

---

near/nep141-locker/src/errors.rs
near/nep141-locker/src/lib.rs
near/nep141-locker/src/storage.rs
near/omni-types/src/lib.rs

- Make the storage upgradable by introducing `TransferMessageStorage` type.
- Replace `unwrap_or_else` with `SdkExpect`
- Introduce storage management.
- Add API to retrieve required storage deposits for different actions.

NEP141-Locker: implement storage deposit

---

evm/bridge-token-factory/contracts/BridgeTokenFactory.sol
evm/bridge-token-factory/contracts/BridgeTokenFactoryWormhole.sol
evm/bridge-token-factory/test/BridgeToken.js
evm/bridge-token-factory/test/BridgeTokenWormhole.js
near/omni-types/src/evm_events.rs

- Rename `withdraw` and `deposit` to `initTransfer` and `finTransfer` accordingly.
- Make EVM event types consistent
- Pass fee to `initTransfer` function

NEP141-Locker: consistent events types and methods naming

---

near/nep141-locker/src/lib.rs

https://github.com/AuditOneAuditReviews/Omnibridge-audit-review/issues/21

fix: verify emitter address on binding token

---

.github/workflows/ci.yaml
.github/workflows/lints.yaml
Makefile
near/mock/mock-prover/src/lib.rs
near/mock/mock-token/src/lib.rs
near/nep141-locker/src/lib.rs
near/nep141-locker/src/storage.rs
near/omni-prover/evm-prover/src/lib.rs
near/omni-prover/wormhole-omni-prover-proxy/src/lib.rs
near/omni-prover/wormhole-omni-prover-proxy/src/parsed_vaa.rs
near/omni-types/src/evm/events.rs
near/omni-types/src/lib.rs
near/omni-types/src/mpc_types.rs
near/omni-types/src/near_events.rs

- Added simple CI with Clippy.
- Made minor changes to address points underlined by clippy.

 Add CI with build and linting 

---

.github/workflows/ci.yaml
Makefile
evm/bridge-token-factory/contracts/BridgeTokenFactory.sol
evm/bridge-token-factory/contracts/BridgeTokenFactoryWormhole.sol
evm/bridge-token-factory/contracts/BridgeTypes.sol
evm/bridge-token-factory/test/BridgeToken.js
evm/bridge-token-factory/test/BridgeTokenWormhole.js
near/mock/mock-prover/src/lib.rs
near/mock/mock-token/src/lib.rs
near/nep141-locker/src/lib.rs
near/nep141-locker/src/storage.rs
near/omni-prover/evm-prover/src/lib.rs
near/omni-prover/wormhole-omni-prover-proxy/src/lib.rs
near/omni-prover/wormhole-omni-prover-proxy/src/parsed_vaa.rs
near/omni-tests/src/lib.rs
near/omni-types/src/evm/events.rs
near/omni-types/src/evm/mod.rs
near/omni-types/src/lib.rs
near/omni-types/src/locker_args.rs
near/omni-types/src/mpc_types.rs
near/omni-types/src/near_events.rs

- https://github.com/Near-One/omni-bridge/pull/65
- https://github.com/Near-One/omni-bridge/pull/64
- https://github.com/Near-One/omni-bridge/pull/51
- https://github.com/Near-One/omni-bridge/pull/78
- https://github.com/Near-One/omni-bridge/pull/83
- https://github.com/Near-One/omni-bridge/pull/85
- https://github.com/Near-One/omni-bridge/pull/68
- https://github.com/Near-One/omni-bridge/pull/88
- https://github.com/Near-One/omni-bridge/pull/89
- https://github.com/Near-One/omni-bridge/pull/80
- https://github.com/Near-One/omni-bridge/pull/91

chore: merge develop 

---

evm/bridge-token-factory/contracts/BridgeTokenFactory.sol
evm/bridge-token-factory/contracts/BridgeTokenFactoryWormhole.sol
evm/bridge-token-factory/contracts/BridgeTypes.sol
near/nep141-locker/src/lib.rs
near/nep141-locker/src/storage.rs
near/nep141-locker/src/tests/lib_test.rs
near/omni-prover/wormhole-omni-prover-proxy/src/parsed_vaa.rs
near/omni-tests/src/lib.rs
near/omni-types/src/evm/events.rs
near/omni-types/src/lib.rs
near/omni-types/src/sol_address.rs
near/omni-types/src/tests/lib_test.rs

- Implemented EVM locker
- Changed the interface of the `EVM::initTransfer`, so it now accepts the token address instead of the token ID and message instead of `near_account_id:msg`.
- Map the token address and ID in both directions on the Near side to get the token ID by the address.
- Added the `SolAddress` type with validation.
Todo in follow-up PRs:
- Rename the factory contract and move the hardhat project to evm dir.
- Implement factory on Near

feat: EVM locker implementation

---

.gitignore
Makefile
evm/bridge-token-factory/contracts/BridgeTokenFactory.sol
evm/bridge-token-factory/contracts/BridgeTokenFactoryWormhole.sol
evm/bridge-token-factory/contracts/BridgeTypes.sol
near/Cargo.lock
near/Cargo.toml
near/nep141-locker/src/lib.rs
near/omni-prover/evm-prover/src/lib.rs
near/omni-prover/wormhole-omni-prover-proxy/src/lib.rs
near/omni-prover/wormhole-omni-prover-proxy/src/parsed_vaa.rs
near/omni-token/Cargo.toml
near/omni-token/src/lib.rs
near/omni-token/src/omni_ft.rs
near/omni-types/src/evm/events.rs
near/omni-types/src/lib.rs
near/omni-types/src/locker_args.rs
near/omni-types/src/prover_result.rs
near/omni-types/src/sol_address.rs
near/omni-types/src/tests/lib_test.rs
near/token-deployer/Cargo.toml
near/token-deployer/src/lib.rs

The PR implement the NEAR token factory to bridge the none-NEAR first tokens to Near and other chains.
1. Added token deployer contract.
2. Added the token contract with mint and burn methods.
3. Implemented the factory logic in the locker contract.
4. Added support for native tokens transfers from the EVMs

feat: implement NEAR token factory

---

evm/bridge-token-factory/contracts/Borsh.sol
evm/bridge-token-factory/contracts/BridgeTokenFactory.sol
evm/bridge-token-factory/contracts/BridgeTokenFactoryWormhole.sol
evm/bridge-token-factory/contracts/BridgeTypes.sol
near/nep141-locker/src/lib.rs
near/nep141-locker/src/storage.rs
near/nep141-locker/src/tests/lib_test.rs
near/omni-prover/wormhole-omni-prover-proxy/src/parsed_vaa.rs
near/omni-tests/src/lib.rs
near/omni-types/src/evm/events.rs
near/omni-types/src/lib.rs
near/omni-types/src/near_events.rs
near/omni-types/src/prover_result.rs
near/omni-types/src/tests/lib_test.rs

-  Introduce `destination_nonce` and track it for every chain separately
- Use the `TransferId` to to identify the transfer on all chains.
- Use `uint64` instead of `uint128` for nonces.

feat: support different nonces for different chains

---

near/nep141-locker/src/lib.rs

- The `set_token_metadata` has weaker access rustication due to `MetadataManager`, so we should prevent updating the decimals for security reasons.
- Don't allow logging empty metadata.

fix: don't allow decimals update

---

near/nep141-locker/src/lib.rs
near/nep141-locker/src/tests/lib_test.rs
near/omni-tests/src/fin_transfer.rs
near/omni-types/src/locker_args.rs

- Refactored the storage deposit arguments.
- Added verification for of storage deposit for the native token.
- Removed the hardcoded `NEP141_DEPOSIT` amount, the relayer now needs to set this value.

fix: mint native fee on fin_transfer

---

near/omni-tests/src/fin_transfer.rs

With https://github.com/Near-One/omni-bridge/pull/117, we no longer need this adjustment for extra NEAR.
Closes #94

fix: Remove excess storage deposit in test

---

.github/workflows/rust.yaml
Makefile
near/Cargo.lock
near/Cargo.toml
near/omni-tests/Cargo.toml
near/omni-tests/src/fin_transfer.rs

- Switching to `nextest` for parallel test execution
- Consolidating build & test jobs to reduce GitHub Actions overhead
- Using `dtolnay/rust-toolchain` instead of `actions-rs/toolchain`
- Setting up proper Rust caching with workspace-aware configuration
- Enabling aggressive crate caching for both lint and build jobs
- Splitting test build/run for better cache utilization
- Converting test cases to use `rstest` for better parameterization
- Replacing manual test tables with cleaner `#[case]` syntax
- Making test failure messages more descriptive
All checks remain the same - just way faster now 🚀

Speed up CI and modernize tests

---

near/omni-types/src/lib.rs
near/omni-types/src/tests/lib_test.rs

The Rainbow Bridge deploys tokens in this format [<lower_case_hex>.factory.bridge.near](https://nearblocks.io/address/dac17f958d2ee523a2206206994597c13d831ec7.factory.bridge.near), after the migration we are going to use `factory.bridge.near` as deployer and the tokens for ethereum chain will be deployed in the same format.

Backward compatible address prefix for ETH network

---

near/omni-bridge/src/lib.rs

- Added pausable macro
- Moved the private function to the private module

Add pausable macro to NEAR methods

---

omni-relayer/clippy.toml
omni-relayer/example-mainnet-config.toml
omni-relayer/example-testnet-config.toml
omni-relayer/src/startup/evm.rs
omni-relayer/src/startup/mod.rs
omni-relayer/src/startup/near.rs
omni-relayer/src/startup/solana.rs
omni-relayer/src/utils/evm.rs
omni-relayer/src/utils/redis.rs
omni-relayer/src/utils/solana.rs
omni-relayer/src/utils/storage.rs
omni-relayer/src/workers/evm.rs
omni-relayer/src/workers/solana.rs

Just to add some clarity, I want to provide a small explanation why do we need this logic
These are account keys that we can get from `raw_message.account_keys`:
```txt
Account Keys: ["BXss9YNCX2p6VPf2Em54pHXkXnC2FPBeZgbB9fY1cuBR", "DsR6nocBnnkmRdRNYCXtXoNsdTKfa9Kd4ZdcxJEZJeKv", "79nePUUxtfJSdrkbririgL5YMaoEh5g4HNQaar2EuJ7", "dahPEoZGXfyV58JqqH85okdHmpN8U2q8owgPUXSCPxe", "2yVjuQwpsvdsrywzs
JJVs9Ueh4zayyo5DYJbBNc3DDpn", "3ZLekZYq2qkZiSpnSvabjit34tUkjSwD1JFuW9as9wBG", "6tckHFBpiJ8YgYN8FUskvtvTpXQZ55g5LHeo1kvELoDQ", "9bFNrXNb2WTx8fMHXCheaZqkLZ3YCCaiqTftHxeintHy", "G7BgdUgsQ7iQmHUqPM85XvantPDqHxEi88Fs23FeDTLo", "11
111111111111111111111111111111", "SysvarC1ock11111111111111111111111111111111", "SysvarRent111111111111111111111111111111111", "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", …
```

feat: constructed persistent account keys from instruction

---

.github/workflows/e2e-test.yml

The dummy pipeline is required to test the pipeline from another PR.
If the pipeline must be triggered manually, it can't be tested from PR unless its version is already in the main branch.

Add dummy GA pipeline for E2E tests

---

omni-relayer/src/startup/evm.rs
omni-relayer/src/startup/mod.rs
omni-relayer/src/startup/solana.rs

In the worst case scenario when there's no network connection relayer will try to reconnect to rpc providers every 5 seconds instead of dying silently
closes #220

fix: restart ws connection to rpc when it was dropped

---

omni-relayer/src/main.rs
omni-relayer/src/startup/evm.rs
omni-relayer/src/startup/solana.rs

We found an issue when connection can be dropped right when new event should be found, so we need to fetch everything from the last_processed_block

fix: restart ws connection to rpc when it was dropped and sync lost blocks

---

.github/workflows/build-contracts.yaml

Reverts Near-One/omni-bridge#231
Reason: https://github.com/Near-One/omni-bridge/actions/runs/13221464115/job/36907014544#step:10:7

Revert "fix: replaced deprecated release action"

---

near/omni-bridge/src/lib.rs
near/omni-bridge/src/tests/lib_test.rs

The existing token resolution system is split into two functions:
- `get_token_address`: converts NEAR tokens to foreign chain addresses
- `get_token_id`: converts foreign chain addresses to NEAR tokens
This creates several issues:
1. No direct way to resolve foreign chain to foreign chain addresses (e.g., ETH->Solana)
2. Developers need to chain functions manually, increasing complexity and error risk
3. Unclear documentation leads to confusion when first encountering the system
4. Inconsistent error handling between the two functions
This PR introduces a new universal resolution function that:
- Enables foreign chain to foreign chain resolution using NEAR as an intermediary
- Provides a single, clear interface for all token address resolution needs
- Maintains backwards compatibility …

Universal Token Address Resolution

---

near/omni-bridge/src/lib.rs
near/omni-bridge/src/tests/lib_test.rs

The existing token resolution system is split into two functions:
- `get_token_address`: converts NEAR tokens to foreign chain addresses
- `get_token_id`: converts foreign chain addresses to NEAR tokens
This creates several issues:
1. No direct way to resolve foreign chain to foreign chain addresses (e.g., ETH->Solana)
2. Developers need to chain functions manually, increasing complexity and error risk
3. Unclear documentation leads to confusion when first encountering the system
4. Inconsistent error handling between the two functions
This PR introduces a new universal resolution function that:
- Enables foreign chain to foreign chain resolution using NEAR as an intermediary
- Provides a single, clear interface for all token address resolution needs
- Maintains backwards compatibility …

Token resolution

---

near/omni-bridge/src/lib.rs
near/omni-bridge/src/storage.rs
near/omni-types/src/lib.rs

The fast relayer could use external protocols to hold and swap liquidity so that the sender_id will be the protocol contract instead of the real relayer ID. 
In the PR, the relayer id should be passed in the `FastFinTransferMsg`.

feat: pass the fast relayer over `FastFinTransferMsg`

---

near/Cargo.lock
near/omni-types/Cargo.toml
near/omni-types/src/lib.rs

This is useful to avoid casting with `as`

Cast ChainKind to u8

---

evm/hardhat.config.ts
evm/src/omni-bridge/contracts/OmniBridge.sol

The ability to receive Ether is necessary to facilitate the migration from Rainbow Bridge. Ether must be locked in this contract to enable unlock operations, so we need to transfer Ether to this contract from the EthCustodian.

Add the ability to receive ETH in Omni Bridge.

---

omni-relayer/Cargo.lock
omni-relayer/Cargo.toml
omni-relayer/src/main.rs
omni-relayer/src/startup/evm.rs

For some reason log doesn't provide information about timestamp (my guess that this is an issue with infura rpc), so we have to fetch block to get timestamp

fix: timestamps for evm events

---

dist-workspace.toml
omni-relayer/Cargo.lock
omni-relayer/Cargo.toml
omni-relayer/example-devnet-config.toml
omni-relayer/example-mainnet-config.toml
omni-relayer/example-testnet-config.toml
omni-relayer/src/config.rs
omni-relayer/src/utils/fee.rs
omni-relayer/src/workers/mod.rs

Right now everyone could sign transfer manually and since we didn't check fee after receiving `SignEvent` relayer would pay for any transfer without even checking if provided fee will be enough to cover cost of the transfer

fix: check fee before finalizing transfer

---

near/omni-bridge/src/lib.rs
near/omni-tests/src/lib.rs
near/omni-tests/src/native_fee_role.rs

Aurora cannot attach NEAR tokens to cover storage costs and fees. To address this limitation:
1. Aurora could pre-deposit large amounts of NEAR (e.g., 100 NEAR) to cover storage costs for these transfers
2. The contract currently manages two types of balances:
- Storage deposit balance (tracked in `accounts_balances`)
- Native fee handling for cross-chain transfers
The issue exists in how native fees are processed during `ft_on_transfer`:
```rust
let transfer_message = TransferMessage {
// ...other fields...
fee: Fee {
fee: parsed_msg.fee,
native_fee: parsed_msg.native_token_fee,
},
// ...other fields...
};
// Add the native_token_fee to required_storage_balance
required_storage_balance = required_storage_balance
.saturating_add(NearToken::from_yoctonear(parsed_msg.native_token_fee.0)); …
```

feat: add native fee restriction

---

evm/src/eNear/contracts/ENearProxy.sol
evm/src/eNear/contracts/FakeProver.sol
evm/src/eNear/contracts/IENear.sol
evm/src/eNear/scripts.ts
evm/tests/eNearProxy.test.ts

Allow the e-near proxy contract to finalize the legacy transfers

fix: finalise legacy transfers

---

near/omni-bridge/src/lib.rs
near/omni-bridge/src/storage.rs
near/omni-tests/src/fast_transfer.rs
near/omni-types/src/lib.rs

https://github.com/AuditOneAuditReviews/Omnibridge3-audit-review/issues/31 - add payable attribute to `storage_unregister`
https://github.com/AuditOneAuditReviews/Omnibridge3-audit-review/issues/13 - convert storage_deposit_amount from u128 to U128
https://github.com/AuditOneAuditReviews/Omnibridge3-audit-review/issues/8 - add additional checks when completing fast transfer (not a vulnerability but as a good practice)
https://github.com/AuditOneAuditReviews/Omnibridge3-audit-review/issues/1 - get rid of `unwrap`'s
https://github.com/AuditOneAuditReviews/Omnibridge3-audit-review/issues/32 - transfer tokens in `storage_withdraw`

fix: fast transfers audit fixes

---

migration/verification/verify-paused-methods.ts

This PR adds functionality to verify the pause status of Aurora Engine precompiles and ETH connector methods.
- Added a new `checkAuroraPrecompiles` function to verify the status of EXIT_TO_NEAR and EXIT_TO_ETHEREUM precompiles
- Implemented ETH connector flags verification to check if ft_transfer and ft_transfer_call methods are paused
- Interprets precompile flags where:
- EXIT_TO_NEAR = bit 0 (value 1)
- EXIT_TO_ETHEREUM = bit 1 (value 2)
- Handles ETH connector pause flags:
- PAUSE_DEPOSIT = bit 0 (value 1)
- PAUSE_WITHDRAW = bit 1 (value 2)
- PAUSE_FT = bit 2 (value 4)
- Recognizes special case flag value 255 for pausing all functions
The verification tool has been tested against Aurora Localnet and correctly identifies the pause status of precompiles and ETH connector methods.

feat: Aurora Migration Verification

---

near/Cargo.lock
near/omni-types/Cargo.toml
near/omni-types/src/lib.rs

This is a request from Igor Kazakov and overall I think it would be very neat for UX. Right now we have to specify chain_kind in "Title case" in api, sdk, rpc
closes https://github.com/Near-One/bridge-indexer-rs/issues/142

chore: lowercase and title-case serialization

---

near/omni-bridge/src/lib.rs
near/omni-tests/src/omni_token.rs

Some of the migrated Rainbow tokens don't have the metadata, for example, this one https://github.com/aurora-is-near/bridge-assets/pull/326.
This PR allows setting decimal by DAO over the `set_token_metadata`

feat: update decimals over `set_token_metadata`

---

near/omni-bridge/src/lib.rs

We missed that in case of a fast transfer native token needs to be retrieved from origin message

Fix fast tranfser native fee

---

near/Cargo.lock
near/mock/mock-token/src/lib.rs
near/omni-bridge/src/lib.rs
near/omni-bridge/src/storage.rs
near/omni-prover/wormhole-omni-prover-proxy/src/lib.rs
near/omni-prover/wormhole-omni-prover-proxy/src/parsed_vaa.rs
near/omni-types/Cargo.toml
near/omni-types/src/evm/events.rs
near/omni-types/src/evm/header.rs
near/omni-types/src/evm/receipt.rs
near/omni-types/src/lib.rs
near/omni-types/src/sol_address.rs
near/omni-types/src/tests/lib_test.rs
omni-relayer/src/config.rs
omni-relayer/src/utils/nonce.rs
solana/bridge_token_factory/programs/bridge_token_factory/src/instructions/admin/update_metadata.rs
solana/bridge_token_factory/programs/bridge_token_factory/src/instructions/user/log_metadata.rs
solana/bridge_token_factory/programs/bridge_token_factory/src/state/used_nonces.rs

This should help to get rid of [`OmniAddressWrapper`](https://github.com/Near-One/bridge-indexer-rs/blob/7aa8fc4bf4c4621da115b98742577862fecc3d4b/omni-indexer-enricher/src/enricher.rs#L45) in our enricher

chore: derived `Hash` trait for `OmniAddress`

---

near/omni-bridge/src/lib.rs
near/omni-tests/src/fast_transfer.rs
near/omni-types/src/lib.rs

In this PR we add an additional field called `origin_amount` to the Fast Transfer message. It serves no behavioral purpose but acts as an additional safety check to make sure the amount submitted for the fast transfer is correct. This is important because, in case of a mistake, the relayer will not be able to recover the funds when transfer reaches finality.
For consistency we can also change the `fee` property of the message to contain normalized amount. I didn't do it to keep the change less invasive but I believe it's worth considering

Safety check for fast transfer amount

---

omni-relayer/Cargo.lock
omni-relayer/Cargo.toml
omni-relayer/example-devnet-config.toml
omni-relayer/example-mainnet-config.toml
omni-relayer/example-testnet-config.toml
omni-relayer/src/config.rs
omni-relayer/src/main.rs
omni-relayer/src/startup/bridge_indexer.rs
omni-relayer/src/startup/evm.rs
omni-relayer/src/startup/near.rs
omni-relayer/src/startup/solana.rs
omni-relayer/src/utils/bridge_api.rs
omni-relayer/src/utils/near.rs
omni-relayer/src/utils/redis.rs
omni-relayer/src/utils/solana.rs
omni-relayer/src/workers/evm.rs
omni-relayer/src/workers/mod.rs
omni-relayer/src/workers/near.rs
omni-relayer/src/workers/solana.rs

This feature is needed to prevent double signing from omni relayer and satoshi relayer. Normally satoshi's relayer would sign a transaction, but if their relayer will have any issues, we can manually allow our relayer to sign transactions

feat: added flag to enable/disable `sign_btc_transaction` call

---

omni-relayer/Cargo.lock
omni-relayer/Cargo.toml
omni-relayer/src/config.rs

Break would've worked if we somehow checked that `replace` operation was successful, but `replace` method doesn't return anything. Instead, we're just checking that env variable is there, which is incorrect. Let's say we want to replace `TATUM_API_KEY`. Right now we will just retrieve `INFURA_API_KEY` from env since it's first in the loop, replace nothing and break, leaving other api placeholders untouched

fix: config env replacement
