near/nep141-locker/src/lib.rs, near/nep141-locker/src/storage.rs, near/omni-tests/src/lib.rs
* Check the deposit and refund
* ix the annotation of bind_token_callback to ensure consistency with the prover
* Make bind_token_callback payable 
* https://github.com/orgs/Near-One/projects/3/views/1?pane=issue&itemId=82324067&issue=Near-One%7Comni-bridge%7C61
=> [OmniBridge]: Fix bind token in NEP141-Locker

omni-relayer/Cargo.lock, omni-relayer/Cargo.toml, omni-relayer/config.toml, omni-relayer/src/config.rs, omni-relayer/src/main.rs, omni-relayer/src/startup/evm.rs, omni-relayer/src/utils/near.rs, omni-relayer/src/utils/redis.rs, omni-relayer/src/workers/evm.rs, omni-relayer/src/workers/near.rs
=> feat: claim native fee

evm/bridge-token-factory/contracts/BridgeTokenFactory.sol, evm/bridge-token-factory/contracts/BridgeTokenFactoryWormhole.sol, evm/bridge-token-factory/contracts/BridgeTypes.sol, evm/bridge-token-factory/test/BridgeToken.js, evm/bridge-token-factory/test/BridgeTokenWormhole.js
- Removed the unused whitelist logic to improve code readability and contract size.
- Move types to separate libraries to improve code readability.
- Fixed tests
=> EVM-Factory: Cleanup and remove whitelist

near/nep141-locker/src/lib.rs
https://github.com/AuditOneAuditReviews/Omnibridge-audit-review/issues/16
=> Fix: fix typo

near/omni-prover/evm-prover/src/lib.rs
https://github.com/AuditOneAuditReviews/Omnibridge-audit-review/issues/27
=> fix: replace `assert` with `require`

near/nep141-locker/src/lib.rs
https://github.com/AuditOneAuditReviews/Omnibridge-audit-review/issues/18
=> fix: increase `required_deposit` due to `ONE_YOCTO`

near/nep141-locker/src/lib.rs
https://github.com/AuditOneAuditReviews/Omnibridge-audit-review/issues/20
=> fix: fix update fee

omni-relayer/Cargo.lock, omni-relayer/Cargo.toml, omni-relayer/src/startup/evm.rs, omni-relayer/src/utils/near.rs
This fixes borsh serialization issues
=> chore: updated omni types

near/omni-prover/wormhole-omni-prover-proxy/src/lib.rs, near/omni-prover/wormhole-omni-prover-proxy/src/parsed_vaa.rs
- Fixed decode abi issue
- Fixed the return type from json to proof
- Fixed decoding `emitter_address` 
- Fixed gas error
=> fix: fix Wormhole prover

evm/bridge-token-factory/contracts/BridgeTokenFactory.sol, evm/bridge-token-factory/contracts/BridgeTypes.sol, near/nep141-locker/src/lib.rs, near/nep141-locker/src/tests/lib_test.rs, near/omni-tests/src/lib.rs, near/omni-types/src/lib.rs, near/omni-types/src/locker_args.rs, near/omni-types/src/near_events.rs
Claim native tokens on NEAR side, by minting native tokens instead of claiming fee in the source chain.
=> feat: claim native fee on NEAR side

near/nep141-locker/src/lib.rs, near/token-deployer/src/lib.rs
- Simplify json api for `deploy_native_token`.
-  Fix token deployer
=> fix deploy native token

.catalog-info.yaml, near/omni-token/.catalog-info.yaml, solana/bridge_token_factory/.catalog-info.yaml
Adds omni-token and solana bridge-token-factory to catalog-info
=> chore: update catalog-info

near/omni-bridge/src/lib.rs
Issue: https://github.com/Near-One/omni-bridge/issues/165
=> Fix: don't burn the fee on ft_on_transfer

evm/.openzeppelin/arbitrum-one.json, evm/.openzeppelin/base.json, evm/hardhat.config.ts, evm/src/omni-bridge/contracts/OmniBridge.sol
- Added setter for near bridge-derived address
- Fixed deploy script
- Upgraded the mainnet contracts
=> Add setter for near bridge derived address

solana/bridge_token_factory/programs/bridge_token_factory/build.rs
=> chore: update default program id

omni-relayer/Cargo.lock, omni-relayer/Cargo.toml, omni-relayer/clippy.toml, omni-relayer/src/config.rs, omni-relayer/src/main.rs, omni-relayer/src/startup/evm.rs, omni-relayer/src/utils/mod.rs, omni-relayer/src/utils/nonce.rs, omni-relayer/src/workers/evm.rs, omni-relayer/src/workers/near.rs, omni-relayer/src/workers/solana.rs
Now it can handle multiple events at the same time:
closes #238
=> fix: manage near and evm nonces using mutex

README.md
- Update link for omnibridge docs (path altered slightly)
- Added PR welcome
- Update TG support badge
=> fix: update docs link & badge edit

solana/bridge_token_factory/programs/bridge_token_factory/src/instructions/admin/change_config.rs, solana/bridge_token_factory/programs/bridge_token_factory/src/instructions/admin/initialize.rs, solana/bridge_token_factory/programs/bridge_token_factory/src/instructions/admin/mod.rs, solana/bridge_token_factory/programs/bridge_token_factory/src/instructions/admin/pause.rs, solana/bridge_token_factory/programs/bridge_token_factory/src/instructions/admin/update_metadata.rs, solana/bridge_token_factory/programs/bridge_token_factory/src/lib.rs, solana/bridge_token_factory/programs/bridge_token_factory/src/state/config.rs
- `update_metadata` method for updating metadata uri
- `metadata_admin` role that can update metadata
=> Solana: Add update metadata method and an updater role

omni-relayer/Cargo.lock, omni-relayer/Cargo.toml, omni-relayer/example-devnet-config.toml, omni-relayer/example-mainnet-config.toml, omni-relayer/example-testnet-config.toml, omni-relayer/src/utils/fee.rs
Related to https://github.com/Near-One/bridge-indexer-rs/pull/140
=> fix: transfer fee request

omni-relayer/Cargo.lock, omni-relayer/Cargo.toml, omni-relayer/src/main.rs
https://github.com/rustls/rustls/issues/1938
=> fix: rustls install default

.github/workflows/release.yml, dist-workspace.toml, omni-relayer/Cargo.lock, omni-relayer/Cargo.toml, omni-relayer/deny.toml, omni-relayer/src/startup/evm.rs, omni-relayer/src/startup/mod.rs, omni-relayer/src/startup/near.rs, omni-relayer/src/utils/nonce.rs
https://github.com/Near-One/omni-bridge/actions/runs/13804272274/job/38612146256
https://github.com/axodotdev/cargo-dist/issues/1576#issuecomment-2504094102
=> fix: relayer compilation on linux

migration/verification/verify-contract-hash.sh
closes https://github.com/Near-One/omni-bridge-private/issues/37
=> feat: added script to verify contract hash

omni-relayer/Cargo.lock, omni-relayer/Cargo.toml, omni-relayer/example-testnet-config.toml, omni-relayer/src/startup/bridge_indexer.rs, omni-relayer/src/startup/evm.rs, omni-relayer/src/utils/evm.rs, omni-relayer/src/workers/mod.rs
=> fix: known relayer issues after migration

omni-relayer/.example-env, omni-relayer/Cargo.lock, omni-relayer/Cargo.toml, omni-relayer/src/config.rs, omni-relayer/src/main.rs, omni-relayer/src/startup/bridge_indexer.rs, omni-relayer/src/startup/evm.rs, omni-relayer/src/startup/mod.rs, omni-relayer/src/startup/near.rs, omni-relayer/src/startup/solana.rs, omni-relayer/src/utils/bridge_api.rs, omni-relayer/src/utils/evm.rs, omni-relayer/src/utils/near.rs, omni-relayer/src/utils/nonce.rs, omni-relayer/src/utils/redis.rs, omni-relayer/src/utils/solana.rs, omni-relayer/src/workers/btc.rs, omni-relayer/src/workers/evm.rs, omni-relayer/src/workers/mod.rs, omni-relayer/src/workers/near.rs, omni-relayer/src/workers/solana.rs
=> chore: push logs to Loki

near/Cargo.lock, near/Cargo.toml, near/omni-bridge/Cargo.toml, near/omni-prover/evm-prover/Cargo.toml, near/omni-prover/omni-prover/Cargo.toml, near/omni-prover/omni-prover/src/lib.rs, near/omni-prover/wormhole-omni-prover-proxy/Cargo.toml, near/omni-token/Cargo.toml, near/token-deployer/Cargo.toml
Removed since it can be done using batches
=> feat: removed `add_provers` method

near/Cargo.lock, near/Cargo.toml, near/mock/mock-token-receiver/Cargo.toml, near/mock/mock-token-receiver/src/lib.rs, near/omni-bridge/src/lib.rs, near/omni-tests/Cargo.toml, near/omni-tests/src/fast_transfer.rs, near/omni-tests/src/fin_transfer.rs, near/omni-tests/src/helpers.rs, near/omni-types/src/near_events.rs
This PR adds refund logic in case the `ft_on_transfer` fails
=> feat: implement refund

omni-relayer/Cargo.lock, omni-relayer/Cargo.toml, omni-relayer/example-devnet-config.toml, omni-relayer/example-mainnet-config.toml, omni-relayer/example-testnet-config.toml, omni-relayer/src/config.rs, omni-relayer/src/startup/bridge_indexer.rs, omni-relayer/src/startup/evm.rs, omni-relayer/src/startup/mod.rs, omni-relayer/src/utils/near.rs, omni-relayer/src/utils/nonce.rs, omni-relayer/src/workers/evm.rs, omni-relayer/src/workers/mod.rs
Should be merged after https://github.com/Near-One/bridge-sdk-rs/pull/173
=> fix: adapted to new sdk version

.github/workflows/omni-relayer-docker.yml, omni-relayer/Dockerfile
Creates a Docker image that we can deploy anywhere
=> feat: add Docker image for omni-relayer

omni-relayer/Cargo.lock, omni-relayer/Cargo.toml, omni-relayer/example-devnet-config.toml, omni-relayer/example-mainnet-config.toml, omni-relayer/example-testnet-config.toml, omni-relayer/src/config.rs, omni-relayer/src/main.rs, omni-relayer/src/startup/bridge_indexer.rs, omni-relayer/src/startup/evm.rs, omni-relayer/src/startup/mod.rs, omni-relayer/src/startup/near.rs, omni-relayer/src/startup/solana.rs, omni-relayer/src/utils/bridge_api.rs, omni-relayer/src/utils/evm.rs, omni-relayer/src/utils/near.rs, omni-relayer/src/utils/redis.rs, omni-relayer/src/utils/solana.rs, omni-relayer/src/workers/btc.rs, omni-relayer/src/workers/evm.rs, omni-relayer/src/workers/mod.rs, omni-relayer/src/workers/near.rs, omni-relayer/src/workers/solana.rs
Should be merged only after https://github.com/Near-One/bridge-sdk-rs/pull/179
=> fix: covered more cases that we should retry

.github/workflows/omni-relayer-docker.yml
- Adds a Warp Builder with proper caching. Reduces CI time from ~9 minutes to ~2 minutes (with a warm cache)
=> feat(docker): use Warp Builder

omni-relayer/Cargo.lock, omni-relayer/Cargo.toml, omni-relayer/example-devnet-config.toml, omni-relayer/example-testnet-config.toml, omni-relayer/src/workers/near.rs
This should be merged after all sdk-related PRs and after version update in Cargo.toml
=> chore: update versions
